package com.cucumber.StepsDefinitions;

import UtilitiesFactory.UtilFactory;
import com.cucumber.Enums.APIEnumVariables;
import com.cucumber.Enums.EnumVariables;
import com.cucumber.Enums.IMTEnumVariables;
import io.restassured.response.Response;
import org.json.simple.JSONObject;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class HarnessVariables extends UtilFactory {
    public HarnessVariables() throws Exception {
    }
    protected static JSONObject request,expectedResponse;
    protected static Response response;
    protected static Map responseData = new HashMap<>();
    protected static String BUILD_NUMBER = APIEnumVariables.BUILD_NUMBER.getValue();
    protected static String TRANSACTION_TIME;
    protected static String RANDOM_TEXT;
    protected static String RANDOM_MSISDN;
    protected static String WALLET_BALANCE;
    protected static String ENTERED_AMOUNT;
    protected static String VALIDATION_TEXT;
    protected static List<String> AGENTS;
    protected static List<String> MERCHANTS;
    protected static String SAVED_BANK;
    protected static String PARTNER_NAME = "MONEYGRAM";
    protected static String IMT_PRODUCT;
    protected static Boolean REWARD_FLAG = false;
    protected static int INVITE_PENDING_COUNT;
    protected static String SAVED_CARD = EnumVariables.SAVED_CARD.getValue();
    protected static String SUCCESSFUL_CASH_GIFT_MSG = EnumVariables.SUCCESSFUL_CASH_GIFT_MSG.getValue();
    protected static String SUCCESSFUL_ADD_MONEY_MSG = EnumVariables.SUCCESSFUL_ADD_MONEY_MSG.getValue();
    protected static String SUCCESSFUL_VOUCHER_PURCHASE_MSG = EnumVariables.SUCCESSFUL_VOUCHER_PURCHASE_MSG.getValue();
    protected static String SUCCESSFUL_ADD_ACCOUNT_MSG = EnumVariables.SUCCESSFUL_ADD_ACCOUNT_MSG.getValue();
    protected static String SUCCESSFUL_DELETE_ACCOUNT_MSG = EnumVariables.SUCCESSFUL_DELETE_ACCOUNT_MSG.getValue();
    protected static String SUCCESSFUL_DIRECT_PAY_TRANSFER_MSG = EnumVariables.SUCCESSFUL_DIRECT_PAY_TRANSFER_MSG.getValue();
    protected static String CONTACT_US_MOBILE_NUMBER = EnumVariables.CONTACT_US_MOBILE_NUMBER.getValue();
    protected static String PAYMENT_MACHINES_TEXT = EnumVariables.PAYMENT_MACHINES_TEXT.getValue();
    protected static String IMT_TRANSACTION_FEE = IMTEnumVariables.IMT_TRANSACTION_FEE.getValue();
    protected static String IMT_VAT = IMTEnumVariables.IMT_VAT.getValue();
    protected static String IMT_CASH_PICKUP = IMTEnumVariables.IMT_CASH_PICKUP.getValue();
    protected static String IMT_SEND_TO_BANK = IMTEnumVariables.IMT_SEND_TO_BANK.getValue();
    protected static String IMT_SEND_TO_MOBILE_WALLET = IMTEnumVariables.IMT_SEND_TO_MOBILE_WALLET.getValue();
    protected static String IMT_PAKISTAN = IMTEnumVariables.IMT_PAKISTAN.getValue();
    protected static String IMT_GHANA = IMTEnumVariables.IMT_GHANA.getValue();
    protected static String IMT_PHILIPPINES = IMTEnumVariables.IMT_PHILIPPINES.getValue();
    protected static String SEND_MONEY_VAT = EnumVariables.SEND_MONEY_VAT.getValue();
    protected static String SEND_MONEY_FEE = EnumVariables.SEND_MONEY_FEE.getValue();
    protected static String SUCCESSFUL_SEND_MONEY_AGENT_MSG = EnumVariables.SUCCESSFUL_SEND_MONEY_AGENT_MSG.getValue();
    protected static String SUCCESSFUL_TOP_UP_ETISALAT_MSG = EnumVariables.SUCCESSFUL_TOP_UP_ETISALAT_MSG.getValue();
    protected static String SUCCESSFUL_TOP_UP_DU_MSG = EnumVariables.SUCCESSFUL_TOP_UP_DU_MSG.getValue();
    protected static String SUCCESSFUL_TOP_UP_NATIONAL_BOND_MSG = EnumVariables.SUCCESSFUL_TOP_UP_NATIONAL_BOND_MSG.getValue();
    protected static String SUCCESSFUL_TOP_UP_SALIK_MSG = EnumVariables.SUCCESSFUL_TOP_UP_SALIK_MSG.getValue();
    protected static String SUCCESSFUL_PAY_BILLS_AJMAN_MSG = EnumVariables.SUCCESSFUL_PAY_BILLS_AJMAN_MSG.getValue();
    protected static String SEND_TO_BANK_FEE = EnumVariables.SEND_TO_BANK_FEE.getValue();
    protected static String SEND_TO_BANK_VAT = EnumVariables.SEND_TO_BANK_VAT.getValue();
    protected static String SUCCESSFUL_SEND_TO_BANK_MSG = EnumVariables.SUCCESSFUL_SEND_TO_BANK_MSG.getValue();
    protected static String SUCCESSFUL_ADD_MONEY_FROM_BANK_MSG = EnumVariables.SUCCESSFUL_ADD_MONEY_FROM_BANK_MSG.getValue();
    protected static String SUCCESSFUL_LINKED_BANK_MSG = EnumVariables.SUCCESSFUL_LINKED_BANK_MSG.getValue();
    protected static String SUCCESSFUL_UNLINKED_BANK_MSG = EnumVariables.SUCCESSFUL_UNLINKED_BANK_MSG.getValue();
    protected static String SUCCESSFUL_LINKED_CARD_MSG = EnumVariables.SUCCESSFUL_LINKED_CARD_MSG.getValue();
    protected static String SUCCESSFUL_UNLINKED_CARD_MSG = EnumVariables.SUCCESSFUL_UNLINKED_CARD_MSG.getValue();
    protected static String SUCCESSFUL_TRANSFER_MSG = EnumVariables.SUCCESSFUL_TRANSFER_MSG.getValue();
    protected static String RECEIVER_FIRST_NAME_FIELD = IMTEnumVariables.RECEIVER_FIRST_NAME_FIELD.getValue();
    protected static String RECEIVER_FIRST_NAME_WITHOUT_SLASH_FIELD = IMTEnumVariables.RECEIVER_FIRST_NAME_WITHOUT_SLASH_FIELD.getValue();
    protected static String RECEIVER_LAST_NAME_FIELD = IMTEnumVariables.RECEIVER_LAST_NAME_FIELD.getValue();
    protected static String RECEIVER_LAST_NAME_WITHOUT_SLASH_FIELD = IMTEnumVariables.RECEIVER_LAST_NAME_WITHOUT_SLASH_FIELD.getValue();
    protected static String SENDER_OCCUPATION_FIELD = IMTEnumVariables.SENDER_OCCUPATION_FIELD.getValue();
    protected static String PURPOSE_OF_TRANSACTION_FIELD = IMTEnumVariables.PURPOSE_OF_TRANSACTION_FIELD.getValue();
    protected static String SOURCE_OF_FUNDS_FIELD = IMTEnumVariables.SOURCE_OF_FUNDS_FIELD.getValue();
    protected static String RELATIONSHIP_TO_RECEIVER_FIELD = IMTEnumVariables.RELATIONSHIP_TO_RECEIVER_FIELD.getValue();
    protected static String ACCOUNT_NUMBER_FIELD = IMTEnumVariables.ACCOUNT_NUMBER_FIELD.getValue();
    protected static String BANK_NAME_FIELD = IMTEnumVariables.BANK_NAME_FIELD.getValue();
    protected static String MOBILE_WALLET_FIELD = IMTEnumVariables.MOBILE_WALLET_FIELD.getValue();
    protected static String MOBILE_WALLET_FIELD_WU = IMTEnumVariables.MOBILE_WALLET_FIELD_WU.getValue();
    protected static String RECEIVER_WALLET_NUMBER_FIELD = IMTEnumVariables.RECEIVER_WALLET_NUMBER_FIELD.getValue();
    protected static String RECEIVER_MOBILE_NUMBER_FIELD = IMTEnumVariables.RECEIVER_MOBILE_NUMBER_FIELD.getValue();
    protected static String PURPOSE_OF_REMITTANCE_FIELD = IMTEnumVariables.PURPOSE_OF_REMITTANCE_FIELD.getValue();
    protected static String SENDER_OCCUPATION_VALUE = IMTEnumVariables.SENDER_OCCUPATION_VALUE.getValue();
    protected static String PURPOSE_OF_TRANSACTION_VALUE = IMTEnumVariables.PURPOSE_OF_TRANSACTION_VALUE.getValue();
    protected static String SOURCE_OF_FUNDS_VALUE = IMTEnumVariables.SOURCE_OF_FUNDS_VALUE.getValue();
    protected static String RELATIONSHIP_TO_RECEIVER_VALUE = IMTEnumVariables.RELATIONSHIP_TO_RECEIVER_VALUE.getValue();
    protected static String BANK_NAME_VALUE = IMTEnumVariables.BANK_NAME_VALUE.getValue();
    protected static String BANK_NAME_VALUE_WU = IMTEnumVariables.BANK_NAME_VALUE_WU.getValue();
    protected static String BANK_ACCOUNT_NUMBER_VALUE = IMTEnumVariables.BANK_ACCOUNT_NUMBER_VALUE.getValue();
    protected static String MOBILE_WALLET_VALUE = IMTEnumVariables.MOBILE_WALLET_VALUE.getValue();
    protected static String MOBILE_WALLET_VALUE_WU = IMTEnumVariables.MOBILE_WALLET_VALUE_WU.getValue();
    protected static String RECEIVER_WALLET_NUMBER_VALUE = IMTEnumVariables.RECEIVER_WALLET_NUMBER_VALUE.getValue();
    protected static String RECEIVER_MOBILE_NUMBER_VALUE = IMTEnumVariables.RECEIVER_MOBILE_NUMBER_VALUE.getValue();
    protected static String PURPOSE_OF_REMITTANCE_VALUE = IMTEnumVariables.PURPOSE_OF_REMITTANCE_VALUE.getValue();
    protected static String SUCCESSFUL_IMT_TRANSFER_MSG = IMTEnumVariables.SUCCESSFUL_IMT_TRANSFER_MSG.getValue();
    protected static String SUCCESSFUL_PAY_BILLS_ADDC_MSG = EnumVariables.SUCCESSFUL_PAY_BILLS_ADDC_MSG.getValue();
    protected static String SUCCESSFUL_PAY_BILLS_AADC_MSG = EnumVariables.SUCCESSFUL_PAY_BILLS_AADC_MSG.getValue();
    protected static String UPGRADE_ACCOUNT_FLOW_MSG = EnumVariables.UPGRADE_ACCOUNT_FLOW_MSG.getValue();
    protected static String SUCCESSFUL_INVITE_MSG = EnumVariables.SUCCESSFUL_INVITE_MSG.getValue();
    protected static String ALREADY_REGISTERED_INVITE_MSG = EnumVariables.ALREADY_REGISTERED_INVITE_MSG.getValue();
    protected static String SUCCESSFUL_REQUEST_MONEY_MSG = EnumVariables.SUCCESSFUL_REQUEST_MONEY_MSG.getValue();
}
